
[AboutE]
Meter=String
MeterStyle=Side
Text=#About#
Hidden=0
Y=(227)*#scaledpi#
x=(25)*#scaledpi#



[Titlke]
Meter=String
x=(220)*#scaledpi#
y=(40)*#scaledpi#
MeterStyle=Default
Text=Big Sur #Version# (RC1)
fontsize=(19)*#scaledpi#
LeftMouseUpAction=!execute ["http://screenstyler.com/?ref=bigsur"]
MouseActionCursor=1
ToolTipText=Visit website and check for updates
[Menu]
Meter=String
MeterStyle=Default
Text=A macOS Big Sur-inspired spinoff off of Omnimo
x=(2)*#scaledpi#r
y=(10)*#scaledpi#R
fontsize=(9)*#scaledpi#


[Try]
Meter=String
MeterStyle=Default
Text=Also try the original Windows-styled version! -->
x=r
y=(1)*#scaledpi#R
fontsize=(10)*#scaledpi#
fontcolor=239,130,0

[te]
meter=string
MeterStyle=Default
x=r
y=(10)*#scaledpi#R
fontsize=(8)*#scaledpi#
text=Created by fediaFedia#crlf#Thanks to LEX, Maiguris, dtaf_alonso, smurfier, jsmorley, cfixd and Ciel
stringstyle=bold

[t2]
meter=string
MeterStyle=Default
x=r
w=(420)*#scaledpi#
h=(90)*#scaledpi#
ClipString=1
fontcolor=#textcolor2#,120
y=(10)*#scaledpi#R
fontsize=(7)*#scaledpi#
text=Big Sur, iOS, Apple Watch are trademarks of the Apple Computer Corporation in the US. BigSur for Rainmeter was created for customization purposes only, with no intent to infringe upon the trademarks of Apple Computer in the U.S. and/or other countries. The project is not using, even partially, any resources from the aforementioned sources has been done entirely from scratch.#crlf##crlf#GNU v2 / Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


[t3]
meter=string
MeterStyle=Default
x=r
w=(420)*#scaledpi#
h=(90)*#scaledpi#
ClipString=1
fontcolor=#textcolor2#,255
y=(10)*#scaledpi#R
fontsize=(11)*#scaledpi#
text=Also check out ScreenStyler.com. A new styling initiative designed #crlf#to make it easier and more fun!
LeftMouseUpAction=!execute ["http://screenstyler.com/?ref=bigsur"]
[omnimo]
meter=image
imagename=#@#\Graphics\omnimo.jpg
w=(100)*#scaledpi#
h=(60)*#scaledpi#
x=(540)*#scaledpi#
y=(57)*#scaledpi#


[MeterAlbumMask]
Meter=Image
ImageName=#@#\Graphics\Music\mask4.png
w=(100)*#scaledpi#
h=(60)*#scaledpi#
x=(540)*#scaledpi#
y=(57)*#scaledpi#
imagetint=#colorskin#
LeftMouseUpAction=!execute ["http://omnimo.info?ref=bigsur"]
mouseactioncursor=1