[Variables]
Version=1.3.1
MainLanguage=English
globalblurenable=0
Structure=Structure
blurcornerradius=35
Padding=0
ScaleDpi=1
ThemeFont=SF Pro Display
HideLabels=0
SubstituteFeed="&apos;":"'","&quot;":"","&Quot;":"","&amp;":"&","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":"","&#39;":"'","&#228;":"ä","&#246;":"ö","&#8211;":"–"
SubstituteLink="&amp;":"&","<![CDATA[":"","]]>":""
redcolor=255,90,90
CodePage=0
GlobalWeatherCode=
Opacity=255
title=0
DarkMode=1
ttgallerystyle=dark
OnOff=
textcolor2=255,255,255
colorskin2=0,0,0
InlineShadow=Shadow | 2 | 2 | 3.5 | 0,0,0,150
HideUnits=1
DisplayAMPM=1
TimeFormat=%H:%M
colorskin=30,30,30
FirstTime=0
MissingComponents=!DeactivateConfig
EditManually=0
Draggable=1
opacity2=255
roundness=15
LabelColor=255,255,255
LabelOpacity=255
BlurEnabled=1
BlurType=None
BlurRound=Round
radius=23
IconTint=
IconGreyscale=0
SelectedStyle=Dark

StrokeWidth=0
StrokeColor=200,200,200
StrokeOpacity=255


colorskinGrad=#ColorSkin#
colorskinGradAngle=90
StrokeColorGrad=#StrokeColor#
StrokeAngle=90
ExtrasColor=255,255,255
ExtrasOpacity=100
Latitude=8.684170

[Default]
FontColor=#textcolor2#
FontFace=#ThemeFont#
FontSize=(11)*#scaledpi#
StringAlign=LEFT
AntiAlias=1
