[Variables]
Pictures Folder=%USERPROFILE%\Pictures
Slideshow Speed=5
Subfolders=1
open=["%USERPROFILE%\Pictures"]
next=[!Refresh]
Action=#open#
showpicturestext=1
PicturesButtonAction=#open#
FramePadding=0
KeepAspectRatio=2

;Your Antivirus likely blocked the easy configuration tool, how unlucky for you! Fortunately you can still edit the above value.
;Refresh the skin after saving this file.
height=150
Keep Aspect Ratio=2
Show Filename=[Filename]
