[Variables]
CityName1=Tokyo
CityZone1=+7.0
CityName2=London
CityZone2=+0.0
CityName3=Moscow
CityZone3=+2.0
CityName4=Cupertino
CityZone4=-8.0
24Hour=%H:%M
12Hour=%I:%M %p
ShowSeconds=60

DayLightSavings1=1
DayLightSavings2=0
DayLightSavings3=1
DayLightSavings4=1
DayLightSavings=1:00
hidegrid=1
ClockName=#WorldClock#
CustomCity=Honolulu
CustomTimeZone=-11

;Your Antivirus likely blocked the easy configuration tool, how unlucky for you! Fortunately you can still edit the above value.
;Refresh the skin after saving this file.
